### PR TITLE
Modernize the `active_support` requires

### PR DESCRIPTION
**Pull request by Burgestrand**
We were kind of doing it wrong, and it worked in tests by accident because we required railties and actionpack.

## To do

- [x] I have read the [contributing guidelines](https://github.com/varvet/pundit/contribute).
- [x] I have added relevant tests.
- [x] I have adjusted relevant documentation.
- [x] I have made sure the individual commits are meaningful.
- [x] I have added relevant lines to the CHANGELOG.

PS: Thank you for contributing to Pundit ❤️

### CODE REVIEW

**Comment by anikolaiev** [comment]
@Burgestrand I tried to update to 2.5.0 and now I'm getting an error. I'm using ruby 3.3.5, rails 7.1.5.1
```
An error occurred while loading spec_helper.
Failure/Error: require 'pundit/rspec'

NoMethodError:
  undefined method `deprecator' for module ActiveSupport
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
# ./vendor/bundle/ruby/3.3.0/gems/pundit-2.5.0/lib/pundit/rspec.rb:4:in `<top (required)>'
# ./spec/spec_helper.rb:3:in `<top (required)>'
```

**Comment by Burgestrand** [comment]
> @Burgestrand I tried to update to 2.5.0 and now I'm getting an error. I'm using ruby 3.3.5, rails 7.1.5.1
> 
> ```
> An error occurred while loading spec_helper.
> Failure/Error: require 'pundit/rspec'
> 
> NoMethodError:
>   undefined method `deprecator' for module ActiveSupport
> # ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>'
> # ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
> # ./vendor/bundle/ruby/3.3.0/gems/pundit-2.5.0/lib/pundit/rspec.rb:4:in `<top (required)>'
> # ./spec/spec_helper.rb:3:in `<top (required)>'
> ```
> 
> Any idea how to fix it?

Thanks for letting me know!

Does this fix it?

```ruby
require "pundit" # add this before pundit/rspec
require "pundit/rspec"
```

**Comment by anikolaiev** [comment]
@Burgestrand, yes, that helped. Thank you.

**Comment by Burgestrand** [comment]
@anikolaiev Thanks, that's great! I'll make the appropriate adjustments in Pundit too, so next release you won't need both.

**Pull request merged**
