### PR TITLE
Remove wrong statement for what #authorize returns

### PR DESCRIPTION
**Pull request by mackshkatz**

### CODE REVIEW

**Comment by ce07c3** [comment]
You're reading the documentation on master. The current master has not been published to RubyGems yet. It has been pointed out numerous times but this repo is pretty dead.

**Comment by mackshkatz** [comment]
@ce07c3 oh so which repo is up to date and being maintained?

**Comment by ce07c3** [comment]
None. You can find the docs for your version of Pundit in the relevant branch though. :)

**Comment by mackshkatz** [comment]
Thanks @ce07c3

**Comment by halo** [comment]
I'd say this pull request can be closed. In this particular case it is really the code that needs to adhere to the README, not the other way around :)

**Comment by fwolfst** [comment]
@halo I disagree. The README should then either state in a warning-kind-of tone: "You are reading the README of Pundit 'master' which might not be released yet (current release is ...)" or have more detailled installation instructions (as 'gem pundit' in the Gemfile will not be enough). Anyway - a bit a sad story. Pundit is such a nice solution.

**Comment by ce07c3** [comment]
Why was this merged @ingemar? The document correctly reflects the code in the master branch.  The readme is now incorrect for the code in the same repo.

**Comment by ce07c3** [comment]
@fwolfst I agree with you, however: there should be a warning.

**Comment by halo** [comment]
>  it is really the code that needs to adhere to the README 

@fwolfst Sorry for the confusion. By that I meant that the code on Rubygems should be updated so that it adheres to whatever is on Github. The code in master was already in sync with the README (as @ce07c3 just pointed out). 

This merge should be reverted and a new gem version published in the near future.

**Comment by ce07c3** [comment]
Definitely revert.

**Comment by fwolfst** [comment]
We are on the same side, guys. And it looks as if things move. Btw awesome effort, @ce07c3 ! Thanks a lot.

**Pull request merged**
