### PR TITLE
updating rubocop config file

### PR DESCRIPTION
**Pull request by MarceloAGuimaraes**
https://github.com/varvet/pundit/issues/701

### CODE REVIEW

**Comment by Burgestrand** [comment]
Hi! Thanks for doing this work, but your PR is _adding_ warnings to our rubocop CI, not removing them.

I'm trying to aggressively clean up this repo so I'll close this PR. That doesn't mean the discussion ends, but with the current rubocop version/config there are no `rubocop.yml` warnings in main.

**Comment by MarceloAGuimaraes** [comment]
@Burgestrand , maybe we can think to upgrade the rubocop to a new version. They already released the 1.24, but the minimum ruby to this version is the 2.5.0. 
Do we have a problem with this requirement ?

**Comment by Burgestrand** [comment]
> @Burgestrand , maybe we can think to upgrade the rubocop to a new version. They already released the 1.24, but the minimum ruby to this version is the 2.5.0. Do we have a problem with this requirement ?

That should be OK, the oldest version of Ruby that we support is typically the oldest non-EOL Ruby from https://www.ruby-lang.org/en/downloads/ — today that's 2.6. Anything older we can ignore.

**Comment by MarceloAGuimaraes** [comment]
Awesome. I just created the pr https://github.com/varvet/pundit/pull/708.

**Pull request closed without merging**
