### PR TITLE
Add information about namespaced policies

### PR DESCRIPTION
**Pull request by DanAndreasson**
I couldn't find any information about namespaced policies anywhere

### CODE REVIEW

**Comment by ramaboo** [comment]
Check out https://github.com/elabs/pundit/pull/391. I have been doing a fair bit of work on the namespace stuff. I agree the docs could be better. I was kinda waiting for #391 to get approved though before writing all that.

**Comment by DanAndreasson** [comment]
@ramaboo Alright! 

Is this changes still accurate when/if your PR get merged?

**Comment by DanAndreasson** [comment]
@ramaboo how is your PR progressing? 

Will changes in this PR still be applicable when/if #391 is merged? If so, can we merge this?

**Comment by ramaboo** [comment]
This will work for now. After #391 is merged I can write a more detailed guide on all the stuff this change enables.

**Comment by ramaboo** [comment]
There are other pull requests to with doc changes as well that are equally good.. The way we use it is we link our subdomains to our policies so visits to admin.ourcompany.com trigger the policy [:admin, object] and visits to sales.ourcompany.com would trigger [:sales, object] etc. It allows a centralized place for policies across 10 apps.

**Comment by Linuus** [comment]
Closing in favor of: #392

**Pull request closed without merging**
