### PR TITLE
fix PolicyFinder when given an array with policy class override

### PR DESCRIPTION
**Pull request by ryanhertz**
When trying to find a policy using an array, the `policy_class` override method was not getting called on the last item of the array.

### CODE REVIEW

**Comment by ryanhertz** [comment]
@damien @jnicklas Can this be merged? It's my first real OS pr.

**Comment by mikaellisselgard** [comment]
What the status on this one? Policies are currently broken when trying to use the namespace functionality used in #331. Anything I can do?

**Comment by armchairdj** [comment]
Please merge this! I have now forked Pundit twice, once last year and once just now after pulling upstream changes from the last few months, to fix this same issue. And my fix was not nearly as elegant! Kudos to @ryanhertz for tackling it!

**Comment by Linuus** [comment]
This looks good to me. Thanks @ryanhertz !

**Comment by halo** [comment]
Just to mention it for posterity. I use [Draper](https://github.com/drapergem/draper) and occasionally try to authorize a `Draper::CollectionDecorator` like so:

```ruby
def index
  @articles = authorize scope.decorate
end
```

For whatever reason, the `Draper::CollectionDecorator` masks [as an Array](https://github.com/drapergem/draper/blob/master/lib/draper/collection_decorator.rb#L63-L66). Since this change, Pundit tries to find a Policy with the name "Article::Article::Article::ArticlePolicy", depending on the number of records in the Array 😆 

I know, I shouldn't be using Draper at all, but I thought I'd just mention the conflict here.

May I also ask how this pull request is related to https://github.com/varvet/pundit/issues/351 ? Do they interfere with each other? Does this one fix the other one? Or are they not related? I'm just trying to make sense out of the code.

Thank you for your hard work!

**Comment by Linuus** [comment]
@halo #351 is not really related to this one. The problem here is that if you override the `policy_class` method on the object being authorized it wouldn't call it if used with the namespacing functionality, e.g. `authorize [:admin, @article]`.

We still always pass the entire array to the policy in the end. I'm not sure if that will change yet.

**Pull request merged**
