### PR TITLE
Add documentation for namespace support; resolves #373

### LINKED ISSUE #373: Add namespaces support to documentation
Namespaces support was added on #331, however the documentation for that features is missing in the README.

### PR DESCRIPTION
**Pull request by daveriess**

### CODE REVIEW

**Comment by brunowego** [comment]
Please consider merge it. This is a good explanation about how uses pundit inside namespaces.

**Comment by laertispappas** [comment]
+1

**Comment by ttrmw** [comment]
👍 this was helpful, more so than #410 imo

**Comment by Linuus** [comment]
Thanks!

**Comment by laertispappas** [comment]
Can we also merge the fix please? https://github.com/varvet/pundit/pull/391

**Pull request merged**
